languageCode = "en-us"
title = "Suru (する)"
theme = "dopetrope"

[author]
  name = "Bodie Solomon"
  homepage = "https://github.com/jbsolomon"

[params.doc]
    title = "Docs"
    foldername = "doc"
    findoutmoretext = "Start Reading"